import type { Task } from "@entities/task/model/TaskProps";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "Исправить критическую ошибку входа",
    description: "При вводе неверного пароля система падает",
    category: "Bug",
    status: "In Progress",
    priority: "High",
    deadline: "25.06.2025",
  },
  {
    id: 2,
    title: "Добавить темную тему",
    description: "Реализовать переключение между светлой и темной темой",
    category: "Feature",
    status: "To Do",
    priority: "Medium",
    deadline: "26.06.2025",
  },
  {
    id: 3,
    title: "Обновить документацию API",
    description: "Добавить примеры для новых эндпоинтов",
    category: "Documentation",
    status: "Done",
    priority: "Low",
    deadline: "30.06.2025",
  },
  {
    id: 4,
    title: "Оптимизировать работу с базой данных",
    description: "Переписать медленные запросы",
    category: "Refactor",
    status: "In Progress",
    priority: "High",
    deadline: "21.06.2025",
  },
  {
    id: 5,
    title: "Написать тесты для модуля оплаты",
    description: "Покрыть основные сценарии оплаты",
    category: "Test",
    status: "To Do",
    priority: "Medium",
    deadline: "31.06.2025",
  },
  // {
  //   id: 6,
  //   title: "Исправить критическую ошибку входа",
  //   description: "При вводе неверного пароля система падает",
  //   category: "Bug",
  //   status: "In Progress",
  //   priority: "High",
  // },
  // {
  //   id: 7,
  //   title: "Добавить темную тему",
  //   description: "Реализовать переключение между светлой и темной темой",
  //   category: "Feature",
  //   status: "To Do",
  //   priority: "Medium",
  // },
  // {
  //   id: 8,
  //   title: "Обновить документацию API",
  //   description: "Добавить примеры для новых эндпоинтов",
  //   category: "Documentation",
  //   status: "Done",
  //   priority: "Low",
  // },
  // {
  //   id: 9,
  //   title: "Оптимизировать работу с базой данных",
  //   description: "Переписать медленные запросы",
  //   category: "Refactor",
  //   status: "In Progress",
  //   priority: "High",
  // },
  // {
  //   id: 10,
  //   title: "Написать тесты для модуля оплаты",
  //   description: "Покрыть основные сценарии оплаты",
  //   category: "Test",
  //   status: "To Do",
  //   priority: "Medium",
  // },
  // {
  //   id: 11,
  //   title: "Написать тесты для модуля оплаты",
  //   description: "Покрыть основные сценарии оплаты",
  //   category: "Test",
  //   status: "To Do",
  //   priority: "Medium",
  // },
  // {
  //   id: 12,
  //   title: "Исправить критическую ошибку входа",
  //   description: "При вводе неверного пароля система падает",
  //   category: "Bug",
  //   status: "In Progress",
  //   priority: "High",
  // },
  // {
  //   id: 13,
  //   title: "Добавить темную тему",
  //   description: "Реализовать переключение между светлой и темной темой",
  //   category: "Feature",
  //   status: "To Do",
  //   priority: "Medium",
  // },
  // {
  //   id: 14,
  //   title: "Обновить документацию API",
  //   description: "Добавить примеры для новых эндпоинтов",
  //   category: "Documentation",
  //   status: "Done",
  //   priority: "Low",
  // },
  // {
  //   id: 15,
  //   title: "Оптимизировать работу с базой данных",
  //   description: "Переписать медленные запросы",
  //   category: "Refactor",
  //   status: "In Progress",
  //   priority: "High",
  // },
  // {
  //   id: 16,
  //   title: "Написать тесты для модуля оплаты",
  //   description: "Покрыть основные сценарии оплаты",
  //   category: "Test",
  //   status: "To Do",
  //   priority: "Medium",
  // },
];
